[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "radomyr", email = "h.radomyr@proton.me"},
]
dependencies = [
    "pillow>=9.5.0",
    "numpy>=1.24.3",
    "types-Pillow>=9.5.0.2",
]
requires-python = ">=3.11"
license = {text = "GPLv3"}
